# Generated by Django 6.0.3 on 2026-04-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', models.CharField(default='#000000', max_length=7)),
                ('card_color', models.CharField(default='#171717', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('accent', models.CharField(default='#A5CDFE', max_length=7)),
                ('font', models.CharField(default='Poppins', max_length=50)),
            ],
        ),
    ]
